(define (pascal-triangle r c)
  (cond ((= r 0) 1)
		((= c 0) 1)
		((= r c) 1)
		(else (+ (pascal-triangle (- r 1) (- c 1)) (pascal-triangle (- r 1) c)))))
(define (draw-row row)
  )
(define (draw-rows rows count)
  ((draw-row count)
   (if (< count rows)
	 (draw-rows rows (- count 1)))))
(define (draw-triangle rows)
  (draw-rows rows 0))
